[package]
name = "model"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.9"
ndarray = "0.17.1"
ndarray-rand = "0.16.0"
rand = "0.9.2"
rayon = "1.11.0"
serde = {version = "1.0.228", features = ["derive"]}
serde_json = "1.0.145"
